server:
  port: 9000

spring:
  application:
    name: ms-auth
  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    vault:
      uri: http://localhost:8200
      authentication: token
      token:  hvs.pEcDeuKxXk603WbtHSeQ0NMm
      kv:
        enabled: true
        backend: secret
        application-name: ms-auth

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: m9T2x!qLz$g#X8dR5V@h1cZj*K7fNbAe

