server:
  port: 9002

spring:
  application:
    name: ms-ordenes
  datasource:
    url: jdbc:postgresql://localhost:5432/ordenesdb
    username: ${db.username}
    password: ${db.password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    vault:
      token: token-estatico-yahaira
      uri: http://localhost:8200
      authentication: TOKEN
      kv:
        enabled: true
        backend: secret
        application-name: ms-ordenes

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
