server:
  port: 9001

spring:
  application:
    name: ms-productos
  datasource:
    url: jdbc:postgresql://localhost:5432/productosdb
    username: ${db.username}
    password: ${db.password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    vault:
      uri: http://localhost:8200
      token: hvs.s6IfmtU1wo5uFEHoUotKFJ7t
      authentication: TOKEN
      kv:
        enabled: true
        backend: secret
        application-name: ms-productos

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
